# Generated by Django 4.2 on 2023-04-27 06:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content",
            field=ckeditor.fields.RichTextField(default=""),
            preserve_default=False,
        ),
    ]
