# Generated by Django 4.2 on 2023-04-27 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aboutus", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutus",
            options={"verbose_name": "About Us", "verbose_name_plural": "About Us"},
        ),
    ]
