# Generated by Django 4.2 on 2023-04-27 03:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aboutus", "0002_alter_aboutus_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutus",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
